import { EntitiesLocal } from '../../BD/databd';

// E:G filtros OPORTUNIDADES
export const filtersState = [
  {
    label: 'Fecha de Creación',
    value: 'createdAt',
    custom: true,
    customOptions: [
      { value: 'Hoy', label: 'Hoy' },
      { value: 'Semana', label: 'Semana' },
      { value: 'Mes', label: 'Mes' },
      { label: 'Rango', value: 'range', special: 'range' },
    ],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Fecha de Actualización',
    value: 'updatedAt',
    custom: true,
    customOptions: [
      { value: 'Hoy', label: 'Hoy' },
      { value: 'Semana', label: 'Semana' },
      { value: 'Mes', label: 'Mes' },
      { label: 'Rango', value: 'range', special: 'range' },
    ],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Fecha de Cierre',
    value: 'closedAt',
    custom: true,
    customOptions: [
      { value: 'Hoy', label: 'Hoy' },
      { value: 'Semana', label: 'Semana' },
      { value: 'Mes', label: 'Mes' },
      { label: 'Rango', value: 'range', special: 'range' },
    ],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Fecha de Ultimo Seguimiento',
    value: 'lastfollowUpdate',
    custom: true,
    customOptions: [
      { value: 'Hoy', label: 'Hoy' },
      { value: 'Semana', label: 'Semana' },
      { value: 'Mes', label: 'Mes' },
      { label: 'Rango', value: 'range', special: 'range' },
    ],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Fecha de Creación Prospecto',
    value: 'prospectCreatedAt',
    custom: true,
    customOptions: [
      { value: 'Hoy', label: 'Hoy' },
      { value: 'Semana', label: 'Semana' },
      { value: 'Mes', label: 'Mes' },
      { label: 'Rango', value: 'range', special: 'range' },
    ],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Fecha de Actualización Prospecto',
    value: 'prospectUpdatedAt',
    custom: true,
    customOptions: [
      { value: 'Hoy', label: 'Hoy' },
      { value: 'Semana', label: 'Semana' },
      { value: 'Mes', label: 'Mes' },
      { label: 'Rango', value: 'range', special: 'range' },
    ],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Zona geografica',
    value: 'entitiesLocal',
    custom: true,
    customOptions: EntitiesLocal.map((entity) => ({
      value: entity.id,
      label: entity.name,
    })),
    virtualConfig: {
      custom: false,
      label: 'Ciudades',
      value: 'cities',
      valuedbIdName: 'id',
      valuedbFieldName: 'name',
    },
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Categoría de interes',
    value: 'categories',
    valuedbIdName: 'id',
    valuedbFieldName: 'name',
    custom: false,
    customOptions: [],
    operators: [
      { label: 'Es igual a', value: 'igual' },
      { label: 'No es igual a', value: 'no_igual' },
      { label: 'Contiene', value: 'contiene' },
    ],
  },
  {
    label: 'Origen',
    value: 'origins',
    valuedbIdName: 'id',
    valuedbFieldName: 'name',
    custom: false,
    customOptions: [],
    operators: [
      { label: 'Es igual a', value: 'igual' },
      { label: 'No es igual a', value: 'no_igual' },
      { label: 'Contiene', value: 'contiene' },
    ],
  },
  {
    label: 'Fase',
    value: 'phases',
    valuedbIdName: 'id',
    valuedbFieldName: 'name',
    custom: false,
    customOptions: [],
    operators: [
      { label: 'Es igual a', value: 'igual' },
      { label: 'No es igual a', value: 'no_igual' },
      { label: 'Contiene', value: 'contiene' },
    ],
  },
  {
    label: 'Clientes',
    value: 'customers',
    custom: true,
    customOptions: [{ value: 'showClients', label: 'Mostrar clientes' }],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Tipo de clientes',
    value: 'clientTypes',
    valuedbIdName: 'id',
    valuedbFieldName: 'name',
    custom: false,
    customOptions: [],
    operators: [
      { label: 'Es igual a', value: 'igual' },
      { label: 'No es igual a', value: 'no_igual' },
      { label: 'Contiene', value: 'contiene' },
    ],
  },
  {
    label: 'Especialidades',
    value: 'specialties',
    valuedbIdName: 'id',
    valuedbFieldName: 'name',
    custom: false,
    customOptions: [],
    operators: [
      { label: 'Es igual a', value: 'igual' },
      { label: 'No es igual a', value: 'no_igual' },
      { label: 'Contiene', value: 'contiene' },
    ],
  },
  {
    label: 'Rechazadas',
    value: 'rejected',
    custom: true,
    customOptions: [
      { value: 'rejected', label: 'Mostrar rechazados' },
      { value: 'noRejected', label: 'Mostrar No rechazados' },
    ],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Rechazadas',
    value: 'rejected',
    custom: true,
    customOptions: [
      { value: 'rejected', label: 'Mostrar rechazados' },
      { value: 'noRejected', label: 'Mostrar No rechazados' },
    ],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Descartados',
    value: 'discarded',
    custom: true,
    customOptions: [{ label: 'Mostar descartados', value: 'discarded' }],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Importantes',
    value: 'important',
    custom: true,
    customOptions: [{ label: 'Mostar importantes', value: 'important' }],
    operators: [
      { label: 'Mayor que', value: 'mayor_que' },
      { label: 'Menor que', value: 'menor_que' },
      { label: 'Igual', value: 'igual' },
    ],
  },
  {
    label: 'Producto cotizado',
    value: 'products',
    valuedbIdName: 'id',
    valuedbFieldName: 'name',
    custom: false,
    isSearchable: true,
    customOptions: [],
    operators: [
      { label: 'Es igual a', value: 'igual' },
      { label: 'No es igual a', value: 'no_igual' },
      { label: 'Contiene', value: 'contiene' },
    ],
  },
  {
    label: 'Categoria de Producto Cotizado',
    value: 'categories',
    valuedbIdName: 'id',
    valuedbFieldName: 'name',
    custom: false,
    customOptions: [],
    operators: [
      { label: 'Es igual a', value: 'igual' },
      { label: 'No es igual a', value: 'no_igual' },
      { label: 'Contiene', value: 'contiene' },
    ],
  },
];

/* CLIENTES */
// export const filtersState = [
//   {
//     label: 'Fecha de utimo seguimiento',
//     value: 'lastfollowUpdate',
//     custom: true,
//     customOptions: [
//       { value: 'Hoy', label: 'Hoy' },
//       { value: 'Semana', label: 'Semana' },
//       { value: 'Mes', label: 'Mes' },
//       { label: 'Rango', value: 'range', special: 'range' },
//     ],
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Fecha conversion a cliente',
//     value: 'dateConversionClient',
//     custom: true,
//     customOptions: [
//       { value: 'Hoy', label: 'Hoy' },
//       { value: 'Semana', label: 'Semana' },
//       { value: 'Mes', label: 'Mes' },
//       { label: 'Rango', value: 'range', special: 'range' },
//     ],
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Fecha de actualización',
//     value: 'dateUpdate',
//     custom: true,
//     customOptions: [
//       { value: 'Hoy', label: 'Hoy' },
//       { value: 'Semana', label: 'Semana' },
//       { value: 'Mes', label: 'Mes' },
//       { label: 'Rango', value: 'range', special: 'range' },
//     ],
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Zona geografica',
//     value: 'entitiesLocal',
//     // type: 'entitiesLocal',
//     custom: true,
//     customOptions: EntitiesLocal.map((entity) => ({
//       value: entity.id,
//       label: entity.name,
//     })),
//     virtualConfig: {
//       custom: false,
//       label: 'Ciudades',
//       value: 'cities',
//       valuedbIdName: 'id',
//       valuedbFieldName: 'name',
//     },
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Origen',
//     value: 'origins',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Categoría de interes',
//     value: 'categories',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Fase',
//     value: 'phases',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Tipo de clientes',
//     value: 'clientTypes',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Especialidades',
//     value: 'specialties',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Descartados',
//     value: 'discarded',
//     custom: true,
//     customOptions: [{ label: 'Descartados', value: 'discarded' }],
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
// ];

/*PROSPECTOS */
// export const filtersState = [
//   {
//     label: 'Fecha de creación',
//     value: 'createdAt1',
//     // type: 'date1',
//     custom: true,
//     customOptions: [
//       { value: 'Hoy', label: 'Hoy' },
//       { value: 'Semana', label: 'Semana' },
//       { value: 'Mes', label: 'Mes' },
//       { label: 'Rango', value: 'range', special: 'range' },
//     ],
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Fecha de ultimo seguimiento',
//     value: 'createdAt2',
//     // type: 'date2',
//     custom: true,
//     customOptions: [
//       { value: 'Hoy', label: 'Hoy' },
//       { value: 'Semana', label: 'Semana' },
//       { value: 'Mes', label: 'Mes' },
//       { label: 'Rango', value: 'range', special: 'range' },
//     ],
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Fecha de actualización',
//     value: 'createdAt3',
//     // type: 'date3',
//     custom: true,
//     customOptions: [
//       { value: 'Hoy', label: 'Hoy' },
//       { value: 'Semana', label: 'Semana' },
//       { value: 'Mes', label: 'Mes' },
//       { label: 'Rango', value: 'range', special: 'range' },
//     ],
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Licitante',
//     value: 'bidder',
//     // type: 'bidder',
//     custom: true,
//     customOptions: [
//       { label: 'Licitantes', value: 'true' },
//       { label: 'No Licitantes', value: 'false' },
//     ],
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Zona geografica',
//     value: 'entitiesLocal',
//     // type: 'entitiesLocal',
//     custom: true,
//     customOptions: EntitiesLocal.map((entity) => ({
//       value: entity.id,
//       label: entity.name,
//     })),
//     virtualConfig: {
//       custom: false,
//       label: 'Ciudades',
//       value: 'cities',
//       valuedbIdName: 'id',
//       valuedbFieldName: 'name',
//     },
//     operators: [
//       { label: 'Mayor que', value: 'mayor_que' },
//       { label: 'Menor que', value: 'menor_que' },
//       { label: 'Igual', value: 'igual' },
//     ],
//   },
//   {
//     label: 'Proveedor',
//     value: 'providers',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'fullname',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Origen',
//     value: 'origins',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Categoría de interes',
//     value: 'categories',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Fase',
//     value: 'phases',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   // {
//   //   label: 'Compañias',
//   //   value: 'clientsCompanies',
//   //   valuedbIdName: 'id',
//   //   valuedbFieldName: 'companyname',
//   //   custom: false,
//   //   customOptions: [],
//   //   operators: [
//   //     { label: 'Es igual a', value: 'igual' },
//   //     { label: 'No es igual a', value: 'no_igual' },
//   //     { label: 'Contiene', value: 'contiene' },
//   //   ],
//   // },
//   {
//     label: 'Tipo de clientes',
//     value: 'clientTypes',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Especialidades',
//     value: 'specialties',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
//   {
//     label: 'Canales',
//     value: 'channels',
//     valuedbIdName: 'id',
//     valuedbFieldName: 'name',
//     custom: false,
//     customOptions: [],
//     operators: [
//       { label: 'Es igual a', value: 'igual' },
//       { label: 'No es igual a', value: 'no_igual' },
//       { label: 'Contiene', value: 'contiene' },
//     ],
//   },
// ];
