import { createContext, useEffect } from "react";
import { useSelector } from "react-redux";
import {
  AccountBalanceWallet,
  Assessment,
  Assignment,
  AssignmentLate,
  Build,
  BusinessOutlined,
  Category,
  DashboardOutlined,
  BookRounded,
  Flag,
  Group,
  ImportExport,
  Label,
  LibraryBooks,
  MonetizationOn,
  Pages,
  PersonOutline,
  ShoppingBasket,
  Star,
  StarBorder,
  TrackChanges,
  WhatsApp,
  Work,
  ListAlt,
  GroupOutlined,
  LocalActivity,
  Slideshow,
} from "@material-ui/icons";
import { commonSelector } from "../redux/slices/commonSlice";
import { dashboardSelectos } from "../redux/slices/dashboardSlice";
import { userSelector } from "../redux/slices/userSlice";
import useGlobalCommons from "../hooks/useGlobalCommons";
export const CommonFiltersContext = createContext();
export const CommonFiltersProvider = ({ children }) => {
  const {
    phases,
    origins,
    categories,
    groups,
    users,
    clientTypes,
    clientsCompanies,
    specialties,
    goalnames,
    labels,
    entities,
    cities,
    optionIsClient,
    filterRejected,
    filterDescarted,
    filterImportant,
    daysFilter,
    datesStatusOrder,
    taxregime,
    paymentsacount,
    paymentway,
    paymentmethod,
    cfdi,
    filterBill,
    filterIsPaid,
    filterVerified,
    concepts,
    channels,
    products,
    filtersCertainty,
    filterSaleByOrder,
  } = useSelector(commonSelector);
  const {
    totalProspects,
    totalOportunities,
    totalSales,
    totalClients,
    totalPayments,
    totalOrdersEjecutive,
    totalCategories,
    totalProviders,
    totalOrdersAllStatus,
    totalActivities,
  } = useSelector(dashboardSelectos);
  const { id_user, userData } = useSelector(userSelector);

  return (
    <CommonFiltersContext.Provider
      value={{
        directorOptionsProspects: {
          optionsFilters: [
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "ejecutiveId",
              type: "query",
              optionsFilter: users.results,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "inQuery",
              inQueryParent: "ejecutive",
              optionsFilter: groups.results,
            },
            {
              label: "Estado",
              value: "entity",
              getNameChip: "name",
              getValue: "id",
              identifier: "entityId",
              type: "query",
              deleteId: ["cityId"],
              optionsFilter: entities.results,
            },
            {
              label: "Ciudad/Municipio",
              value: "city",
              getNameChip: "name",
              getValue: "id",
              identifier: "cityId",
              type: "query",
              filterBy: "id",
              filterOptions: "value",
              filterInOptions: "entityId",
              optionsFilter: cities.results,
            },
            {
              label: "Categoría de Interés",
              value: "category",
              getNameChip: "name",
              getValue: "id",
              identifier: "categoryId",
              type: "query",
              optionsFilter: categories.results,
            },
            {
              label: "Canal",
              value: "canal",
              getNameChip: "name",
              getValue: "id",
              identifier: "channelId",
              type: "query",
              optionsFilter: channels.results,
            },
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["lastTrackingcreatedAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Descartadas",
              value: "discard",
              getNameChip: "label",
              getValue: "value",
              identifier: "discarted",
              type: "query",
              optionsFilter: filterDescarted,
            },
          ],
        },
        directorOptionsOportunities: {
          optionsFilters: [
            {
              label: "Estado",
              value: "entity",
              getNameChip: "name",
              getValue: "id",
              identifier: "entityId",
              type: "inQuery",
              deleteId: ["cityId"],
              optionsFilter: entities.results,
            },
            {
              label: "Ciudad/Municipio",
              value: "city",
              getNameChip: "name",
              getValue: "id",
              identifier: "cityId",
              type: "inQuery",
              filterBy: "id",
              filterOptions: "value",
              filterInOptions: "entityId",
              optionsFilter: cities.results,
            },
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "ejecutiveId",
              type: "inQuery",
              optionsFilter: users.results,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "inQuery",
              optionsFilter: groups.results,
            },
            {
              label: "Concepto",
              value: "concept",
              getNameChip: "concept",
              getValue: "concept",
              identifier: "concept",
              type: "query",
              optionsFilter: concepts.results,
            },
            {
              label: "Categoría de Interés",
              value: "category",
              getNameChip: "name",
              getValue: "id",
              identifier: "categoryId",
              type: "inQuery",
              optionsFilter: categories.results,
            },
            {
              label: "Origen",
              value: "origin",
              getNameChip: "name",
              getValue: "id",
              identifier: "originId",
              type: "inQuery",
              optionsFilter: origins.results,
            },
            {
              label: "Fase",
              value: "phase",
              getNameChip: "name",
              getValue: "id",
              identifier: "phaseId",
              type: "inQuery",
              optionsFilter: phases.results,
            },
            {
              label: "Clientes",
              value: "client",
              getNameChip: "label",
              getValue: "value",
              identifier: "isclient",
              type: "inQuery",
              optionsFilter: optionIsClient,
            },
            {
              label: "Tipo de Cliente",
              value: "client_type",
              getNameChip: "name",
              getValue: "id",
              identifier: "clientTypeId",
              type: "inQuery",
              optionsFilter: clientTypes.results,
            },
            {
              label: "Compañía",
              value: "company",
              getNameChip: "companyname",
              getValue: "id",
              identifier: "clientCompanyId",
              type: "inQuery",
              optionsFilter: clientsCompanies.results,
            },
            {
              label: "Especialidad",
              value: "specialty",
              getNameChip: "name",
              getValue: "id",
              identifier: "specialtyId",
              type: "inQuery",
              optionsFilter: specialties.results,
            },
            {
              label: "Etiquetas de Prospecto",
              value: "labels",
              getNameChip: "label",
              getValue: "id",
              identifier: "prospectslabels",
              type: "inQuery",
              optionsFilter: labels.results,
            },
            {
              label: "Rechazadas",
              value: "rejected",
              getNameChip: "label",
              getValue: "value",
              identifier: "rejected",
              type: "query",
              optionsFilter: filterRejected,
            },
            {
              label: "Descartadas",
              value: "discard",
              getNameChip: "label",
              getValue: "value",
              identifier: "discarted",
              type: "query",
              optionsFilter: filterDescarted,
            },
            {
              label: "Importantes",
              value: "important",
              getNameChip: "label",
              getValue: "value",
              identifier: "isimportant",
              type: "query",
              optionsFilter: filterImportant,
            },
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["lastTrackingcreatedAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Último Seguimiento",
              value: "lastTrackingcreatedAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "lastTrackingcreatedAt",
              type: "query",
              deleteId: ["createdAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
          ],
        },
        directorOptionsSales: {
          optionsFilters: [
            {
              label: "Estado",
              value: "entity",
              getNameChip: "name",
              getValue: "id",
              identifier: "entityId",
              type: "inQuery",
              deleteId: ["cityId"],
              optionsFilter: entities.results,
            },
            {
              label: "Ciudad/Municipio",
              value: "city",
              getNameChip: "name",
              getValue: "id",
              identifier: "cityId",
              type: "inQuery",
              filterBy: "id",
              filterOptions: "value",
              filterInOptions: "entityId",
              optionsFilter: cities.results,
            },
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "ejecutiveId",
              type: "inQuery",
              optionsFilter: users.results,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "inQuery",
              optionsFilter: groups.results,
            },
            {
              label: "Categoría de Interés",
              value: "category",
              getNameChip: "name",
              getValue: "id",
              identifier: "categoryId",
              type: "inQuery",
              optionsFilter: categories.results,
            },
            {
              label: "Origen",
              value: "origin",
              getNameChip: "name",
              getValue: "id",
              identifier: "originId",
              type: "inQuery",
              optionsFilter: origins.results,
            },
            {
              label: "Fase",
              value: "phase",
              getNameChip: "name",
              getValue: "id",
              identifier: "phaseId",
              type: "inQuery",
              optionsFilter: phases.results,
            },
            {
              label: "Clientes",
              value: "client",
              getNameChip: "label",
              getValue: "value",
              identifier: "isclient",
              type: "inQuery",
              optionsFilter: optionIsClient,
            },
            {
              label: "Tipo de Cliente",
              value: "client_type",
              getNameChip: "name",
              getValue: "id",
              identifier: "clientTypeId",
              type: "inQuery",
              optionsFilter: clientTypes.results,
            },
            {
              label: "Compañía",
              value: "company",
              getNameChip: "companyname",
              getValue: "id",
              identifier: "clientCompanyId",
              type: "inQuery",
              optionsFilter: clientsCompanies.results,
            },
            {
              label: "Especialidad",
              value: "specialty",
              getNameChip: "name",
              getValue: "id",
              identifier: "specialtyId",
              type: "inQuery",
              optionsFilter: specialties.results,
            },
            {
              label: "Etiquetas de Prospecto",
              value: "labels",
              getNameChip: "label",
              getValue: "id",
              identifier: "prospectslabels",
              type: "inQuery",
              optionsFilter: labels.results,
            },
            {
              label: "Rechazadas",
              value: "rejected",
              getNameChip: "label",
              getValue: "value",
              identifier: "rejected",
              type: "query",
              optionsFilter: filterRejected,
            },
            {
              label: "Descartadas",
              value: "discard",
              getNameChip: "label",
              getValue: "value",
              identifier: "discarted",
              type: "query",
              optionsFilter: filterDescarted,
            },
            {
              label: "Importantes",
              value: "important",
              getNameChip: "label",
              getValue: "value",
              identifier: "isimportant",
              type: "query",
              optionsFilter: filterImportant,
            },
            {
              label: "Fecha de Cotización",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["lastTrackingcreatedAt", "soldat"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha de Venta",
              value: "soldat",
              getNameChip: "label",
              getValue: "value",
              identifier: "soldat",
              type: "query",
              deleteId: ["lastTrackingcreatedAt", "createdAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Último Seguimiento",
              value: "lastTrackingcreatedAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "lastTrackingcreatedAt",
              type: "query",
              deleteId: ["createdAt", "soldat"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
          ],
        },
        directorOptionsExecutives: {
          optionsExecutives: [
            {
              value: "byexecutives",
              name: "Ejecutivos",
            },
            {
              value: "bysales",
              name: "Monto de Ventas",
            },
            {
              value: "byoportunities",
              name: "Monto de Oportunidades",
            },
            {
              value: "byprospects",
              name: "Total de Prospectos",
            },
            {
              value: "byprospectsnotviewed",
              name: "Prospectos Sin Visualizar",
            },
            {
              value: "bypending",
              name: "Total de Pendientes",
            },
          ],
          optionsFiltersByTable: [
            {
              identifierTable: "byexecutives",
              optionsBy: [
                {
                  label: "Fecha de Creación",
                  value: "createdAt",
                  getNameChip: "label",
                  getValue: "value",
                  identifier: "createdAt",
                  type: "query",
                  deleteId: ["lastTrackingcreatedAt"],
                  typeof: "date",
                  optionsFilter: daysFilter,
                },
              ],
            },
            {
              identifierTable: "bysales",
              optionsBy: [
                {
                  label: "Fecha de Venta",
                  value: "soldat",
                  getNameChip: "label",
                  getValue: "value",
                  identifier: "soldat",
                  type: "query",
                  typeof: "date",
                  optionsFilter: daysFilter,
                },
              ],
            },
            {
              identifierTable: "byoportunities",
              optionsBy: [
                {
                  label: "Fecha de Oportunidad",
                  value: "createdAt",
                  getNameChip: "label",
                  getValue: "value",
                  identifier: "createdAt",
                  type: "query",
                  typeof: "date",
                  optionsFilter: daysFilter,
                },
              ],
            },
            {
              identifierTable: "byprospects",
              optionsBy: [
                {
                  label: "Fecha Creación",
                  value: "createdAt",
                  getNameChip: "label",
                  getValue: "value",
                  identifier: "createdAt",
                  type: "query",
                  typeof: "date",
                  optionsFilter: daysFilter,
                },
              ],
            },
            {
              identifierTable: "byprospectsnotviewed",
              optionsBy: [
                {
                  label: "Fecha Creación",
                  value: "createdAt",
                  getNameChip: "label",
                  getValue: "value",
                  identifier: "createdAt",
                  type: "query",
                  typeof: "date",
                  optionsFilter: daysFilter,
                },
              ],
            },
            {
              identifierTable: "bypending",
              optionsBy: [
                {
                  label: "Fecha Creación Pendientes",
                  value: "date_from",
                  getNameChip: "label",
                  getValue: "value",
                  identifier: "date_from",
                  type: "query",
                  typeof: "date",
                  optionsFilter: daysFilter,
                },
              ],
            },
          ],
          tableHeadsBy: [
            {
              identifierTable: "byexecutives",
              heads: ["Nombre", "Correo", "Teléfono", "Iniciales", "Grupo"],
            },
            {
              identifierTable: "bysales",
              heads: ["Nombre", "Monto Vendido"],
            },
            {
              identifierTable: "byoportunities",
              heads: ["Nombre", "Monto Cotizado", "Total de Oportunidades"],
            },
            {
              identifierTable: "byprospects",
              heads: ["Nombre", "Prospectos"],
            },
            {
              identifierTable: "byprospectsnotviewed",
              heads: ["Nombre", "Prospectos Sin Visualizar"],
            },

            {
              identifierTable: "bypending",
              heads: ["Nombre", "Pendientes Completados", "Pendientes Incompletos", "Total de Pendientes"],
            },
          ],
          orderByOptions: [
            {
              identifierTable: "byexecutives",
              options: [{ label: "Fecha de Creación", value: "createdAt" }],
            },
            {
              identifierTable: "bysales",
              options: [{ label: "Monto de Venta", value: "totalAmount" }],
            },
            {
              identifierTable: "byoportunities",
              options: [
                { label: "Monto de Cotización", value: "totalAmount" },
                { label: "Total de Oportunidades", value: "totalOportunities" },
              ],
            },
            {
              identifierTable: "byprospects",
              options: [{ label: "Total de Prospectos", value: "totalProspects" }],
            },
            {
              identifierTable: "byprospectsnotviewed",
              options: [{ label: "Total de Prospectos", value: "totalProspects" }],
            },
            {
              identifierTable: "bypending",
              options: [{ label: "Pendientes Incompletos", value: "totalPendings" }],
            },
          ],
        },
        directorOptionsClients: {
          optionsFilters: [
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "ejecutiveId",
              type: "query",
              optionsFilter: users.results,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "inQuery",
              inQueryParent: "ejecutive",
              optionsFilter: groups.results,
            },
            {
              label: "Estado",
              value: "entity",
              getNameChip: "name",
              getValue: "id",
              identifier: "entityId",
              type: "query",
              deleteId: ["cityId"],
              optionsFilter: entities.results,
            },
            {
              label: "Ciudad/Municipio",
              value: "city",
              getNameChip: "name",
              getValue: "id",
              identifier: "cityId",
              type: "query",
              filterBy: "id",
              filterOptions: "value",
              filterInOptions: "entityId",
              optionsFilter: cities.results,
            },
            {
              label: "Categoría de Interés",
              value: "category",
              getNameChip: "name",
              getValue: "id",
              identifier: "categoryId",
              type: "query",
              optionsFilter: categories.results,
            },
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["lastTrackingcreatedAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Descartadas",
              value: "discard",
              getNameChip: "label",
              getValue: "value",
              identifier: "discarted",
              type: "query",
              optionsFilter: filterDescarted,
            },
          ],
        },
        adminAndPursachesOptionsOrders: {
          optionsFilters: [
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["updatedAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha de Actualización",
              value: "updatedAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "updatedAt",
              type: "query",
              deleteId: ["createdAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "inQuery",
              catalogName: "groups",
              optionsFilter: groups.results,
              loadOptions: groups.isFetching,
            },
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "id",
              type: "inQuery",
              catalogName: "executives",
              optionsFilter: users.results,
              loadOptions: users.isFetching,
            },
            {
              label: "Cuenta de Pago",
              value: "paymentaccount",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentaccountId",
              type: "query",
              catalogName: "paymentsacount",
              optionsFilter: paymentsacount.results,
              loadOptions: paymentsacount.isFetching,
            },
            {
              label: "Estado de pedido",
              value: "orderstatus",
              getNameChip: "label",
              getValue: "value",
              identifier: "orderstatusId",
              type: "query",
              optionsFilter: datesStatusOrder,
            },
            {
              label: "Uso De Cfdi",
              value: "cfdi",
              getNameChip: "name",
              getValue: "id",
              identifier: "cfdiId",
              type: "inQuery",
              catalogName: "cfdis",
              optionsFilter: cfdi.results,
              loadOptions: cfdi.isFetching,
            },

            {
              label: "Metodo de Pago",
              value: "paymentmethod",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentmethodId",
              type: "inQuery",
              catalogName: "paymentmethods",
              optionsFilter: paymentmethod.results,
              loadOptions: paymentmethod.isFetching,
            },
            {
              label: "Forma de Pago",
              value: "paymentway",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentwayId",
              type: "inQuery",
              catalogName: "paymentways",
              optionsFilter: paymentway.results,
              loadOptions: paymentway.isFetching,
            },

            {
              label: "Regimen Fiscal",
              value: "taxregime",
              getNameChip: "name",
              getValue: "id",
              identifier: "taxregimeId",
              type: "query",
              catalogName: "taxregimes",
              optionsFilter: taxregime.results,
              loadOptions: taxregime.isFetching,
            },

            {
              label: "Factura",
              value: "bill",
              getNameChip: "label",
              getValue: "value",
              identifier: "billing",
              type: "query",
              optionsFilter: filterBill,
            },
          ],
          orderByOptions: [
            { label: "Fecha Creación ", value: "createdAt" },
            { label: "Fecha Actualización", value: "updatedAt" },
            { label: "Estado de Pedido", value: "orderstatusId" },
          ],
          orderBy: [
            { label: "Descendente", value: "-" },
            { label: "Ascendente ", value: "" },
          ],
        },
        purchasesPurchaseOrders: {
          optionsFilters: [
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["updatedAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha de Actualización",
              value: "updatedAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "updatedAt",
              type: "query",
              deleteId: ["createdAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            }
          ],
          orderByOptions: [
            { label: "Fecha Creación ", value: "createdAt" },
            { label: "Fecha Actualización", value: "updatedAt" }
          ],
          orderBy: [
            { label: "Descendente", value: "-" },
            { label: "Ascendente ", value: "" },
          ],
        },
        adminAndPursachesOptionsSales: {
          optionsFilters: [
            {
              label: "Estado",
              value: "entity",
              getNameChip: "name",
              getValue: "id",
              identifier: "entityId",
              inQueryBy: "prospect",
              deleteId: ["cityId"],
              catalogName: "entities",
              optionsFilter: entities.results,
              loadOptions: entities.isFetching,
            },
            {
              label: "Ciudad/Municipio",
              value: "city",
              getNameChip: "name",
              getValue: "id",
              identifier: "cityId",
              inQueryBy: "prospect",
              filterBy: "id",
              filterOptions: "value",
              filterInOptions: "entityId",
              optionsFilter: cities.results,
              loadOptions: cities.isFetching,
            },
            {
              label: "Categoría de Interés",
              value: "category",
              getNameChip: "name",
              getValue: "id",
              identifier: "categoryId",
              inQueryBy: "prospect",
              catalogName: "categories",
              optionsFilter: categories.results,
              loadOptions: categories.isFetching,
            },
            {
              label: "Contiene Pedido",
              value: "isorder",
              getNameChip: "label",
              getValue: "value",
              identifier: "isorder",
              inQueryBy: null,
              catalogName: null,
              optionsFilter: filterSaleByOrder,
              loadOptions: null,
            },
            {
              label: "Origen",
              value: "origin",
              getNameChip: "name",
              getValue: "id",
              identifier: "originId",
              inQueryBy: "prospect",
              catalogName: "origins",
              optionsFilter: origins.results,
              loadOptions: origins.isFetching,
            },
            {
              label: "Fase",
              value: "phase",
              getNameChip: "name",
              getValue: "id",
              identifier: "phaseId",
              inQueryBy: "prospect",
              catalogName: "phases",
              optionsFilter: phases.results,
              loadOptions: phases.isFetching,
            },
            {
              label: "Tipo de Cliente",
              value: "client_type",
              getNameChip: "name",
              getValue: "id",
              identifier: "clientTypeId",
              inQueryBy: "prospect",
              catalogName: "clientTypes",
              optionsFilter: clientTypes.results,
              loadOptions: clientTypes.isFetching,
            },
            {
              label: "Certeza",
              value: "certainty",
              getNameChip: "label",
              getValue: "value",
              identifier: "certainty",
              inQueryBy: null,
              catalogName: null,
              optionsFilter: filtersCertainty,
            },
            {
              label: "Fecha de Venta",
              value: "soldat",
              getNameChip: "label",
              getValue: "value",
              identifier: "soldat",
              type: "query",
              deleteId: [],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "soldbyId",
              inQueryBy: null,
              catalogName: "executives",
              optionsFilter: users.results,
              loadOptions: users.isFetching,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              inQueryBy: "soldby",
              catalogName: "groups",
              optionsFilter: groups.results,
              loadOptions: groups.isFetching,
            },
          ],
        },
        PursachesOptionsOrders: {
          optionsFilters: [
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["lastTrackingcreatedAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha de Actualización",
              value: "updatedAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "updatedAt",
              type: "query",
              deleteId: ["createdAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "inQuery",
              optionsFilter: groups.results,
            },
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "id",
              type: "inQuery",
              optionsFilter: users.results,
            },
            {
              label: "Cuenta de Pago",
              value: "paymentaccount",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentaccountId",
              type: "query",
              optionsFilter: paymentsacount.results,
            },
            {
              label: "Estado de pedido",
              value: "orderstatus",
              getNameChip: "label",
              getValue: "value",
              identifier: "orderstatusId",
              type: "query",
              optionsFilter: datesStatusOrder,
            },
            {
              label: "Uso De Cfdi",
              value: "cfdi",
              getNameChip: "name",
              getValue: "id",
              identifier: "cfdiId",
              type: "inQuery",
              optionsFilter: cfdi.results,
            },

            {
              label: "Metodo de Pago",
              value: "paymentmethod",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentmethodId",
              type: "inQuery",
              optionsFilter: paymentmethod.results,
            },
            {
              label: "Forma de Pago",
              value: "paymentway",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentwayId",
              type: "inQuery",
              optionsFilter: paymentway.results,
            },

            {
              label: "Regimen Fiscal",
              value: "taxregime",
              getNameChip: "name",
              getValue: "id",
              identifier: "taxregimeId",
              type: "query",
              optionsFilter: taxregime.results,
            },

            {
              label: "Factura",
              value: "bill",
              getNameChip: "label",
              getValue: "value",
              identifier: "billing",
              type: "query",
              optionsFilter: filterBill,
            },
            {
              label: "Verificados",
              value: "verified",
              getNameChip: "label",
              getValue: "value",
              identifier: "isverified",
              type: "query",
              optionsFilter: filterVerified,
            },
          ],
        },
        logisticsOptionsOrders: {
          optionsFilters: [
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["lastTrackingcreatedAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha de Actualización",
              value: "updatedAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "updatedAt",
              type: "query",
              deleteId: ["createdAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "inQuery",
              optionsFilter: groups.results,
            },
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "id",
              type: "inQuery",
              optionsFilter: users.results,
            },
            {
              label: "Cuenta de Pago",
              value: "paymentaccount",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentaccountId",
              type: "query",
              optionsFilter: paymentsacount.results,
            },
            {
              label: "Uso De Cfdi",
              value: "cfdi",
              getNameChip: "name",
              getValue: "id",
              identifier: "cfdiId",
              type: "inQuery",
              optionsFilter: cfdi.results,
            },

            {
              label: "Metodo de Pago",
              value: "paymentmethod",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentmethodId",
              type: "inQuery",
              optionsFilter: paymentmethod.results,
            },
            {
              label: "Forma de Pago",
              value: "paymentway",
              getNameChip: "name",
              getValue: "id",
              identifier: "paymentwayId",
              type: "inQuery",
              optionsFilter: paymentway.results,
            },

            {
              label: "Regimen Fiscal",
              value: "taxregime",
              getNameChip: "name",
              getValue: "id",
              identifier: "taxregimeId",
              type: "query",
              optionsFilter: taxregime.results,
            },

            {
              label: "Factura",
              value: "bill",
              getNameChip: "label",
              getValue: "value",
              identifier: "billing",
              type: "query",
              optionsFilter: filterBill,
            },
          ],
        },
        directorOptionsPayments: {
          optionsFilters: [
            {
              label: "Fecha limite",
              value: "date",
              getNameChip: "label",
              getValue: "value",
              identifier: "date",
              type: "inQuery",
              inQueryParent: "oportunity",
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Se vendió en",
              value: "soldat",
              getNameChip: "label",
              getValue: "value",
              identifier: "soldat",
              type: "inQuery",
              inQueryParent: "oportunity",
              typeof: "soldat",
              optionsFilter: daysFilter,
            },
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "ejecutiveId",
              type: "inQuery",
              optionsFilter: users.results,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "query",
              optionsFilter: groups.results,
            },
            {
              label: "Estatus De Pago",
              value: "ispaid",
              getNameChip: "label",
              getValue: "value",
              identifier: "ispaid",
              type: "query",
              optionsFilter: filterIsPaid,
            },
          ],
        },
        directorOptionsGroups: {
          optionsFilters: [
            {
              label: "Fecha de Venta",
              value: "soldat",
              getNameChip: "label",
              getValue: "value",
              identifier: "soldat",
              type: "inQuery",
              inQueryParent: "oportunity",
              typeof: "date",
              optionsFilter: daysFilter,
            },
          ],
          orderByOptions: [
            {
              label: "Monto Vendido",
              value: "totalAmount",
            },
            // {
            //   label: "Total de Clientes",
            //   value: "totalClients",
            // },
            // {
            //   label: "Total de Prospectos",
            //   value: "totalProspects",
            // },
            // {
            //   label: "Total de Oportunidades ",
            //   value: "totalQuotes",
            // },
          ],
        },
        managerOptionsGoals: {
          optionsFilters: [
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "ejecutiveId",
              type: "query",
              deleteId: ["groupId"],
              optionsFilter: users.results,
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "query",
              deleteId: ["ejecutiveId"],
              typeof: null,
              optionsFilter: groups.results,
            },
            {
              label: "Tipo de Meta",
              value: "goal",
              getNameChip: "name",
              getValue: "id",
              identifier: "goalnameId",
              type: "query",
              deleteId: null,
              typeof: null,
              optionsFilter: goalnames.results,
            },
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["initialperiodate", "finalperiodate"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha Inicio de Periodo",
              value: "initialperiodate",
              getNameChip: "label",
              getValue: "value",
              identifier: "initialperiodate",
              type: "query",
              deleteId: ["createdAt", "finalperiodate"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha Fin de Periodo",
              value: "finalperiodate",
              getNameChip: "label",
              getValue: "value",
              identifier: "finalperiodate",
              type: "query",
              deleteId: ["createdAt", "initialperiodate"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
          ],
        },
        executiveOptionsGoals: {
          optionsFilters: [
            {
              label: "Tipo de Meta",
              value: "goal",
              getNameChip: "name",
              getValue: "id",
              identifier: "goalnameId",
              type: "query",
              deleteId: null,
              typeof: null,
              optionsFilter: goalnames.results,
            },
            {
              label: "Fecha de Creación",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["initialperiodate", "finalperiodate"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha Inicio de Periodo",
              value: "initialperiodate",
              getNameChip: "label",
              getValue: "value",
              identifier: "initialperiodate",
              type: "query",
              deleteId: ["createdAt", "finalperiodate"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Fecha Fin de Periodo",
              value: "finalperiodate",
              getNameChip: "label",
              getValue: "value",
              identifier: "finalperiodate",
              type: "query",
              deleteId: ["createdAt", "initialperiodate"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
          ],
        },
        intelligenceProspects: {
          optionsFilters: [
            {
              label: "Ejecutivo",
              value: "executive",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "ejecutiveId",
              type: "query",
              optionsFilter: users.results,
            },
            {
              label: "Creado por",
              value: "createdby",
              getNameChip: "fullname",
              getValue: "id",
              identifier: "createdbyId",
              type: "query",
              optionsFilter: [
                {
                  id: id_user,
                  fullname: userData?.name,
                },
              ],
            },
            {
              label: "Grupo",
              value: "group",
              getNameChip: "name",
              getValue: "id",
              identifier: "groupId",
              type: "inQuery",
              inQueryParent: "ejecutive",
              optionsFilter: groups.results,
            },

            {
              label: "Estado",
              value: "entity",
              getNameChip: "name",
              getValue: "id",
              identifier: "entityId",
              type: "query",
              deleteId: ["cityId"],
              optionsFilter: entities.results,
            },
            {
              label: "Ciudad/Municipio",
              value: "city",
              getNameChip: "name",
              getValue: "id",
              identifier: "cityId",
              type: "query",
              filterBy: "id",
              filterOptions: "value",
              filterInOptions: "entityId",
              optionsFilter: cities.results,
            },
            {
              label: "Categoría de Interés",
              value: "category",
              getNameChip: "name",
              getValue: "id",
              identifier: "categoryId",
              type: "query",
              optionsFilter: categories.results,
            },
            {
              label: "Prospectos Descartados",
              value: "discard",
              getNameChip: "label",
              getValue: "value",
              identifier: "discarted",
              type: "query",
              optionsFilter: filterDescarted,
            },
            {
              label: "Fecha Alta Prospectos",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["lastTrackingcreatedAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
            {
              label: "Ultimo Seguimiento",
              value: "lastTrackingcreatedAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "lastTrackingcreatedAt",
              type: "query",
              deleteId: ["createdAt"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
          ],
        },
        intelligenceGroups: {
          optionsFilters: [
            {
              label: "Fecha Alta Prospectos",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["initialperiodate", "finalperiodate"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
          ],
        },
        intelligenceEjecutives: {
          optionsFilters: [
            {
              label: "Fecha Alta Prospectos",
              value: "createdAt",
              getNameChip: "label",
              getValue: "value",
              identifier: "createdAt",
              type: "query",
              deleteId: ["initialperiodate", "finalperiodate"],
              typeof: "date",
              optionsFilter: daysFilter,
            },
          ],
        },
        sideBar: {
          optionsSideBar: [
            {
              id: 1,
              role: "ejecutivo",
              isSecondaryOptions: true,
              mainOptions: [
                {
                  identifier: "dashboard",
                  name: "DashBoard",
                  link: "/ejecutivo",
                  style: "dashboard",
                  icon: <DashboardOutlined />,
                  count: null,
                },
                {
                  identifier: "prospects",
                  name: "Prospectos",
                  link: "/prospectos",
                  style: "prospects",
                  icon: <PersonOutline />,
                  count: totalProspects,
                },
                {
                  identifier: "oportunities",
                  name: "Oportunidades",
                  link: "/oportunidades",
                  style: "oportunities",
                  icon: <StarBorder />,
                  count: totalOportunities,
                },
                {
                  identifier: "clients",
                  name: "Clientes",
                  link: "/clientes",
                  style: "clients",
                  icon: <BusinessOutlined />,
                  count: totalClients,
                },
                {
                  identifier: "payments",
                  name: "Cuentas Por Cobrar",
                  link: "/pagos",
                  style: "payments",
                  icon: <MonetizationOn />,
                  count: totalPayments,
                },
                {
                  identifier: "sales",
                  name: "Ventas",
                  link: "/ventas",
                  style: "sales",
                  icon: <AccountBalanceWallet />,
                  count: totalSales,
                },
                {
                  identifier: "orders",
                  name: "Pedidos",
                  link: "/pedidos",
                  style: "orders",
                  icon: <Assignment />,
                  count: totalOrdersEjecutive,
                },
             
                {
                  identifier: "Budget",
                  name: "Presupuestos",
                  link: "/presupuestos",
                  style: "budget",
                  icon: <Slideshow />,
                  count: null,
                },
              ],
              secondaryOptions: [
                {
                  name: "Empresas",
                  link: "/catalogos/empresas",
                  style: "tools",
                  icon: <BusinessOutlined />,
                  subMenu: false,
                },
                {
                  name: "Reportes",
                  link: "/reportes",
                  style: "tools",
                  icon: <Assessment />,
                  subMenu: false,
                },
                {
                  name: "Herramientas",
                  link: null,
                  style: "tools",
                  icon: <Build />,
                  subMenu: true,
                  subOptions: [
                    {
                      name: "Metas",
                      link: "/herramientas/metas",
                      style: "tools",
                      icon: <Star />,
                    },
                    {
                      name: "Plantillas WhatsApp",
                      link: "/herramientas/plantillas",
                      style: "tools",
                      icon: <WhatsApp />,
                    },
                    {
                      name: "Plantillas Observaciones",
                      link: "/herramientas/plantillasObservaciones",
                      style: "tools",
                      icon: <AssignmentLate />,
                    },
                    {
                      name: "Inventario",
                      link: "/inventario",
                      style: "tools",
                      icon: <ListAlt />,
                    },
                  ],
                },
              ],
            },
            {
              id: 2,
              role: "gerente",
              isSecondaryOptions: true,
              mainOptions: [
                {
                  identifier: "dashboard",
                  name: "DashBoard",
                  link: "/gerente",
                  style: "dashboard",
                  icon: <DashboardOutlined />,
                  count: null,
                },
                {
                  identifier: "prospects",
                  name: "Prospectos",
                  link: "/prospectos",
                  style: "prospects",
                  icon: <PersonOutline />,
                  count: totalProspects,
                },
                {
                  identifier: "oportunities",
                  name: "Oportunidades",
                  link: "/oportunidades",
                  style: "oportunities",
                  icon: <StarBorder />,
                  count: totalOportunities,
                },
                {
                  identifier: "clients",
                  name: "Clientes",
                  link: "/clientes",
                  style: "clients",
                  icon: <BusinessOutlined />,
                  count: totalClients,
                },
                {
                  identifier: "sales",
                  name: "Ventas",
                  link: "/ventas",
                  style: "sales",
                  icon: <AccountBalanceWallet />,
                  count: totalSales,
                },
                {
                  identifier: "orders",
                  name: "Pedidos",
                  link: "/pedidos",
                  style: "orders",
                  icon: <Assignment />,
                  count: totalOrdersEjecutive,
                },
                {
                  identifier: "payments",
                  name: "Cuentas Por Cobrar",
                  link: "/pagos",
                  style: "payments",
                  icon: <MonetizationOn />,
                  count: totalPayments,
                },
                {
                  identifier: "executives",
                  name: "Mis Ejecutivos",
                  link: "/ejecutivos",
                  style: "executives",
                  icon: <Group />,
                  count: null,
                },
                          ],
              secondaryOptions: [
                {
                  name: "Reportes",
                  link: "/reportes",
                  style: "tools",
                  icon: <Assessment />,
                  subMenu: false,
                },
                {
                  name: "Catálogos",
                  link: "/reportes",
                  style: "tools",
                  icon: <LibraryBooks />,
                  subMenu: true,
                  subOptions: [
                    {
                      name: "Empresas",
                      link: "/catalogos/empresas",
                      style: "tools",
                      icon: <Work />,
                    },
                    {
                      name: "Fases",
                      link: "/catalogos/fases",
                      style: "tools",
                      icon: <TrackChanges />,
                    },
                    // {
                    //   name: "Etiquetas",
                    //   link: "/catalogos/etiquetas",
                    //   style: "tools",
                    //   icon: <Label />,
                    // },
                  ],
                },
                {
                  name: "Herramientas",
                  link: null,
                  style: "tools",
                  icon: <Build />,
                  subMenu: true,
                  subOptions: [
                    {
                      name: "Metas",
                      link: "/herramientas/metas",
                      style: "tools",
                      icon: <Flag />,
                    },
                    {
                      name: "Importación",
                      link: "/herramientas/importacion",
                      style: "tools",
                      icon: <ImportExport />,
                    },
                    {
                      name: "Plantillas WhatsApp",
                      link: "/herramientas/plantillas",
                      style: "tools",
                      icon: <WhatsApp />,
                    },
                    {
                      name: "Plantillas Observaciones",
                      link: "/herramientas/plantillasObservaciones",
                      style: "tools",
                      icon: <AssignmentLate />,
                    },
                    {
                      name: "Inventario",
                      link: "/inventario",
                      style: "tools",
                      icon: <ListAlt />,
                    },
                  ],
                },
              ],
            },
            {
              id: 3,
              role: "logistica",
              isSecondaryOptions: false,
              mainOptions: [
                {
                  identifier: "orders",
                  name: "Pedidos",
                  link: "/logistica/pedidos",
                  style: "orders",
                  icon: <Assignment />,
                  count: null,
                },
                {
                  name: "Inventario",
                  link: "/inventario",
                  style: "orders",
                  icon: <Assignment />,
                  count: null,
                },
              ],
              secondaryOptions: null,
            },
            {
              id: 4,
              role: "inteligencia_comercial",
              isSecondaryOptions: true,
              mainOptions: [
                {
                  identifier: "prospects",
                  name: "Prospectos",
                  link: "/inteligenciacomercial/prospectos",
                  style: "prospects",
                  icon: <PersonOutline />,
                  count: totalProspects,
                },
                {
                  identifier: "groups",
                  name: "Grupos",
                  link: "/inteligenciacomercial/grupos",
                  style: "groups",
                  icon: <GroupOutlined />,
                  count: groups.count,
                },
                {
                  identifier: "reports",
                  name: "Reportes",
                  link: "/inteligenciacomercial/reportes",
                  style: "reports",
                  icon: <Assignment />,
                  count: null,
                },
              ],
              secondaryOptions: [
                {
                  name: "Herramientas",
                  link: null,
                  style: "tools",
                  icon: <Build />,
                  subMenu: true,
                  subOptions: [
                    {
                      name: "Importación",
                      link: "/herramientas/importacion",
                      style: "tools",
                      icon: <ImportExport />,
                    },
                  ],
                },
              ],
            },
            {
              id: 5,
              role: "administrador_de_ventas",
              isSecondaryOptions: false,
              mainOptions: [
                {
                  identifier: "activities",
                  name: "Actividades",
                  link: "/administracionventas/actividades",
                  style: "activities",
                  icon: <LocalActivity />,
                  count: totalActivities,
                },
                {
                  identifier: "executives",
                  name: "Mis Ejecutivos",
                  link: "/administracionventas/ejecutivos",
                  style: "executives",
                  icon: <Group />,
                  count: null,
                },
              ],
              secondaryOptions: null,
            },
            {
              id: 6,
              role: "compras",
              isSecondaryOptions: false,
              mainOptions: [
                {
                  identifier: "orders",
                  name: "Pedidos",
                  link: "/compras/pedidos",
                  style: "orders",
                  icon: <Assignment />,
                  count: totalOrdersAllStatus,
                },
                {
                  identifier: "products",
                  name: "Productos",
                  link: "/compras/productos",
                  style: "products",
                  icon: <ShoppingBasket />,
                  count: products?.count,
                },
                {
                  identifier: "providers",
                  name: "Proveedores",
                  link: "/compras/proveedores",
                  style: "providers",
                  icon: <LibraryBooks />,
                  count: totalProviders,
                },
                {
                  identifier: "categories",
                  name: "Categorias",
                  link: "/compras/categorias",
                  style: "categories",
                  icon: <Category />,
                  count: totalCategories,
                },
                {
                  identifier: "orders",
                  name: "Ordenes",
                  link: "/compras/ordenes",
                  style: "categories",
                  icon: <BookRounded />,
                  count: totalOrdersEjecutive,
                },
              ],
              secondaryOptions: null,
            },
            {
              id: 7,
              role: "administracion",
              isSecondaryOptions: false,
              mainOptions: [
                // {
                //   identifier: "orders",
                //   name: "Pedidos",
                //   link: "/compras/pedidos",
                //   style: "orders",
                //   icon: <Assignment />,
                //   count: totalOrdersAllStatus,
                // },
                // {
                //   identifier: "products",
                //   name: "Productos",
                //   link: "/compras/productos",
                //   style: "products",
                //   icon: <ShoppingBasket />,
                //   count: products?.count,
                // },
                // {
                //   identifier: "providers",
                //   name: "Proveedores",
                //   link: "/compras/proveedores",
                //   style: "providers",
                //   icon: <LibraryBooks />,
                //   count: totalProviders,
                // },
                // {
                //   identifier: "categories",
                //   name: "Categorias",
                //   link: "/compras/categorias",
                //   style: "categories",
                //   icon: <Category />,
                //   count: totalCategories,
                // },
                {
                  identifier: "orders",
                  name: "Pedidos",
                  link: "/administracion/pedidos",
                  style: "orders",
                  icon: <Assignment />,
                  count: totalOrdersEjecutive,
                },
                {
                  identifier: "sales",
                  name: "Ventas",
                  link: "/administracion/ventas",
                  style: "sales",
                  icon: <AccountBalanceWallet />,
                  count: totalSales,
                },
            
              ],
              secondaryOptions: null,
            },
          ],
        },
      }}
    >
      {children}
    </CommonFiltersContext.Provider>
  );
};
