export const initialFilters = {
  keyword: {
    value: undefined,
    status: 0,
    preLabel: "Correo o Nombre",
  },
  entity: {
    value: undefined,
    label: "",
    preLabel: "Estado",
    status: 0,
  },
  city: { value: undefined, label: "", preLabel: "Ciudad o Municipio", status: 0 },
  origin: {
    value: undefined,
    label: "",
    preLabel: "Origen",
    status: 0,
  },
  phase: {
    value: undefined,
    label: "",
    preLabel: "Origen",
    status: 0,
  },
  clientCompany: {
    value: undefined,
    label: "",
    preLabel: "Empresa",
    status: 0,
  },
  clientType: {
    value: undefined,
    label: "",
    preLabel: "Tipo de Cliente",
    status: 0,
  },
  gender: {
    value: undefined,
    label: "",
    preLabel: "Genero Cliente",
    status: 0,
  },
  discarted: {
    disabled: true,
    value: false,
    status: 0,
  },
};

export const initialEntitiesMap = [
  ["Baja California", "mx-bc", 0],
  ["Baja California Sur", "mx-bs", 0],
  ["Sonora", "mx-so", 0],
  ["Colima", "mx-cl", 0],
  ["Nayarit", "mx-na", 0],
  ["Campeche", "mx-cm", 0],
  ["Quintana Roo", "mx-qr", 0],
  ["Estado de México", "mx-mx", 0],
  ["Morelos", "mx-mo", 0],
  ["Ciudad de México", "mx-cd", 0],
  ["Querétaro", "mx-qt", 0],
  ["Tabasco", "mx-tb", 0],
  ["Chiapas", "mx-cs", 0],
  ["Nuevo León", "mx-nl", 0],
  ["Sinaloa", "mx-si", 0],
  ["Chihuahua", "mx-ch", 0],
  ["Veracruz", "mx-ve", 0],
  ["Zacatecas", "mx-za", 0],
  ["Aguascalientes", "mx-ag", 0],
  ["Jalisco", "mx-ja", 0],
  ["Michoacán", "mx-mi", 0],
  ["Oaxaca", "mx-oa", 0],
  ["Puebla", "mx-pu", 0],
  ["Guerrero", "mx-gr", 0],
  ["Tlaxcala", "mx-tl", 0],
  ["Tamaulipas", "mx-tm", 0],
  ["Coahuila", "mx-co", 0],
  ["Yucatán", "mx-yu", 0],
  ["Durango", "mx-dg", 0],
  ["Guanajuato", "mx-gj", 0],
  ["San Luis Potosí", "mx-sl", 0],
  ["Hidalgo", "mx-hg", 0],
];
